### ISSUE TITLE
elab REPL: internal error: can't introduce here

### ISSUE THREAD

**Issue by cbiffle** [idris-lang/Idris-dev#2700]
Found in 0400a88.

Given an inductive type family, applying the Pruviloj `induction` tactic seems to get things into a state where `intro` no longer works.

Here I've `intro`'d the top-level parameter, applied `induction`, and retired a couple of goals.  I've reached a constructor in the inductive family that takes parameters:

```
----------              Other goals:              ----------
{BLe271},{BNot272},{BAnd273}
----------              Assumptions:              ----------
 b : BExp
----------                 Goal:                  ----------
{BEq270} : (x : AExp) ->
           (x : AExp) ->
           (\subj => beval (optimize_0plus_b subj) = beval subj) (BEq x x)
```

Note that the parameters have the same name.  Odd.

I thought I'd explicitly intro them by name, to give them distinct names:

```
-Main.poohat> intro `{{x}}
INTERNAL ERROR: Can't introduce here.
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
```

Uh-oh.  Maybe `intros` will gensym new names?

```
-Main.poohat> intros
INTERNAL ERROR: Can't introduce here.
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
```

Welp, I'm stuck.

**Comment by david-christiansen** [comment]
Have you tried `attack` before `intros`?

**Comment by david-christiansen** [comment]
If you post the surrounding code, I'll check this out in detail for you.

**Comment by cbiffle** [comment]
Here's a reduced case.  It could almost certainly be reduced further.

```idris
module IntroFail

import Pruviloj
import Pruviloj.Induction

||| An arithmetic expression.
data AExp : Type where
  ANum : Nat -> AExp

||| Evaluation function for arithmetic.
aeval : AExp -> Nat
aeval (ANum k) = k

||| A Boolean expression.
data BExp : Type where
  BTrue : BExp
  BFalse : BExp
  BEq : AExp -> AExp -> BExp

||| Evaluation function for Booleans.
beval : BExp -> Bool
beval BTrue = True
beval BFalse = False
beval (BEq x y) = aeval x == aeval y

||| An "optimization."
bcomm : BExp -> BExp
bcomm (BEq x y) = BEq y x
bcomm x = x

||| Proof that `bcomm` preserves correctness.
bcomm_sound : (b : BExp) -> beval b = beval (bcomm b)
bcomm_sound b = ?bcomm_sound_rhs
```

REPL process to repro:

```
:l IntroFail.idr
:elab IntroFail.bcomm_sound_rhs
intro `{{b}}
induction (Var `{{b}})
compute
exact `(Refl {A=Bool} {x=True})
compute
exact `(Refl {A=Bool} {x=False})
intro `{{x}}
```

Issuing `attack` at this point does unstick the proof, even though it appears (to me) to have no effect beyond renaming the hole:

```
----------              Assumptions:              ----------
 b : BExp
----------                 Goal:                  ----------
{BEq156} : (x : AExp) ->
           (x : AExp) ->
           (\subj => beval subj = beval (bcomm subj)) (BEq x x)

-IntroFail.bcomm_sound_rhs> attack
----------              Other goals:              ----------
{BEq156}
----------              Assumptions:              ----------
 b : BExp
----------                 Goal:                  ----------
{hole59} : (x : AExp) ->
           (x : AExp) ->
           (\subj => beval subj = beval (bcomm subj)) (BEq x x)
```

I'm then able to:

```
intro `{{x}}
intro `{{y}}
compute
```

and the goal reduces to a reflexivity obligation that I have no idea how to solve in this new world, because I can't find either `rewrite` or `reflexivity`, but perhaps that's a story for another bug.

**Comment by david-christiansen** [comment]
Thanks for the report, and thanks for testing these things out!

For the details of `attack`, you can see Edwin's 2013 JFP paper for now. That's high on my list of things that need documentation as well, so getting docs that aren't stuck in some paper somewhere will be an early post-PhD project.

Once you're down to reflexivity, you can do `refine (Var `{Ref})` or `search`. Or, if you're using Pruviloj from the last couple of days, you can use the `reflexivity` tactic to specifically solve trivial equalities without doing a more general proof search.

Really, though, this is the kind of proof that we intend be written as a pattern-matching definition now that our interactive editing tools are reasonable. The tactics are best for writing automatic procedures that dispatch lots of these things! See `test/pruviloj001` in the Idris source for a simple example of that kind of thing that you could adapt to what you're doing here.

**Comment by david-christiansen** [comment]
Here's how I'd prove the lemma that you were working on:
```
natEqRefl : (j, k : Nat) -> j == k = k == j
natEqRefl Z Z = Refl
natEqRefl Z (S k) = Refl
natEqRefl (S j) Z = Refl
natEqRefl (S j) (S k) = natEqRefl j k

||| Proof that `bcomm` preserves correctness.
bcomm_sound : (b : BExp) -> beval b = beval (bcomm b)
bcomm_sound BTrue = Refl
bcomm_sound BFalse = Refl
bcomm_sound (BEq x y) = natEqRefl (aeval x) (aeval y)
```

The interesting thing is really the proof that Boolean equality of Nat is reflexive, which is an interesting fact all on its own.

I'll whip up an elab script for comparison a bit later.

**Comment by david-christiansen** [comment]
Here's how it could be done as an `Elab` script:
```
b <- gensym "b"
intro b
induction (Var b) `andThen` (compute *> try search)
attack
intros
refine (Var `{natEqRefl})
solve
```

The former property is a bit of a pain to do with Elab. I suppose that means I should improve it :-) Doing induction over the result of `aeval x` gives the wrong IH - I think I probably need to hack together a more flexible induction tactic for doing multi-argument families.

**Comment by cbiffle** [comment]
Thanks, David.  I agree that pattern matching is a more appropriate way of attacking this particular problem, but I needed a small problem to learn the elaboration reflection system.  (I'm particularly interested in `induction` over large ADTs, which is an area where pattern-matching proofs -- in my opinion -- quickly become unwieldy.)

My long term interest is in proof automation, but I've gotta start somewhere.

Thanks for the tip on `refine`.  How about `rewrite`?

As for boolean equality being commutative, this is actually in the Bag Of Basic Standard Library Proofs that I hope to submit once the naming question is settled. :-)

**Comment by david-christiansen** [comment]
There's a built-in tactic (in the prelude) called `rewriteWith` that works like the old tactic system's `rewrite` - indeed, it shares an implementation. I called it `rewriteWith` because I wanted to leave `rewrite` open for something a bit more featureful, along the lines of the one in Ssreflect for Coq. I may also remove `rewriteWith` from the primitive tactics implemented in Haskell and push it over to pruviloj - there's really no reason why rewriting has to be primitive other than making sure that the implementation works exactly like the `rewrite ... in ...` syntax.

If you're looking to write automation procedures, then I've found that it's usually easier to develop them incrementally as stand-alone definitions, with `debug` inserted in the spots where it's not done yet. Then, the same automation can be executed on a variety of proof situations at once, which is a bit like a test suite, and also the output from `debug` is a bit easier to follow than the interactive prover, in my opinion.

Something that I expect to become a nice pattern, but that I haven't tried much yet, is taking care of the trivial cases using a small tactic script and then spitting out a bunch of top-level Idris holes to be solved using pattern-matching definitions.

In your case, that can look like:
```
bcomm_sound' : (b : BExp) -> beval b = beval (bcomm b)
bcomm_sound' b = %runElab (do induction (Var `{b}) `andThen` (compute *> try search)
                              metavar "interestingCase")

interestingCase _ _ x y = natEqRefl _ _
```

or even
```
bcomm_sound' : (b : BExp) -> beval b = beval (bcomm b)
bcomm_sound' b =
  %runElab (ignore $ induction (Var `{b}) `andThen`
                       do compute
                          search <|> metavar "interesting")

interesting _ _ _ _ = natEqRefl _ _
```

**Comment by david-christiansen** [comment]
As far as the naming question goes, I think that if you just pick something reasonable and submit a big pile of proofs, that will settle it. The only possible point of contention there is renaming the existing ones to be consistent, which I think is a good idea pre-1.0, but will break some code. It could be easily fixed with a compat lib in `contrib` that re-exports the old names if anyone really needs it though.

**Comment by david-christiansen** [comment]
Another thing that's kind of fun is delegating the inductive definition to a helper, when I realized along the way that it was needed:
```
bcomm_sound' : (b : BExp) -> beval b = beval (bcomm b)
bcomm_sound' =
  %runElab (do b <- gensym "b"
               intro b
               induction (Var b) `andThen`
                 do compute
                    try search
               attack
               nec <- gensym "natEqComm"
               remember nec `((j, k : Nat) -> j == k = k == j)
               attack; intros; metavar "helper"; solve
               vars <- map (\x => the Raw `(aeval ~(Var x))) <$> intros
               exact (mkApp (Var nec) vars)
               solve)

helper b s Z Z = Refl
helper b s Z (S k) = Refl
helper b s (S j) Z = Refl
helper b s (S j) (S k) = IntroFail.helper b s j k
```
I'm not sure why I need to qualify `helper` on the RHS - that's probably a bug somewhere!

This is really not nice code, but hopefully it gives an idea of some possibilities.

**Comment by cbiffle** [comment]
Thanks again, David.  I'm making progress, and will write this up when I've got it working.

I rewrote the case I'm working with to make better use of the `induction` tactic, replacing equality with boolean conjunction:

```idris
module IntroFail

import Pruviloj
import Pruviloj.Induction

||| A Boolean expression.
data BExp : Type where
  BTrue : BExp
  BFalse : BExp
  BAnd : BExp -> BExp -> BExp

||| Evaluation function for Booleans.
beval : BExp -> Bool
beval BTrue = True
beval BFalse = False
beval (BAnd x y) = beval x && beval y

||| An identity transform.
bid : BExp -> BExp
bid (BAnd x y) = BAnd (bid x) (bid y)
bid x = x

||| Proof that the identity transform really is one.
bid_id : (b : BExp) -> beval b = beval (bid b)
bid_id b = ?bid_id_rhs
```

Since both the `BAnd` constructor and the `beval` semantics are now defined recursively, I get to lean harder on `induction`.

(Note: from `master` as of tonight, I still don't see a `reflexivity` tactic in Pruviloj.)

In the interactive shell, I still occasionally get into cases where introduction fails with the error message I initially posted, but I'm applying `attack` as a cargo-cult means to bypass it.  It works.

**Comment by david-christiansen** [comment]
Ah, `reflexivity` is on a branch that I haven't merged yet. Sorry! In the meantime, it's
```
||| A special-purpose tactic that attempts to solve a goal using
||| `Refl`. This is useful for ensuring that goals in fact are trivial
||| when developing or testing other tactics; otherwise, consider
||| using `search`.
reflexivity : Elab ()
reflexivity =
    case !goalType of
      `((=) {A=~A} {B=~_} ~x ~_) =>
        do fill `(Refl {A=~A} {x=~x})
           solve
      _ => fail [ TextPart "The goal is not an equality, so"
                , NamePart `{reflexivity}
                , TextPart "is not applicable."
                ]
```

To be sure to use `attack` properly, you should bracket new bindings with `attack` and `solve`. So `intro`, `forall`, `letbind`, etc should have an `attack` first, and when the hole that the scope over is done, a `solve`. This happened behind the scenes in the old tactic language - it would be possible to write an alternative library for Elab scripts that also automated this, but I want the builtins to be closer to the actual behavior of the elaborator.

**Comment by cbiffle** [comment]
One comment on something way up in the thread:

> the output from debug is a bit easier to follow than the interactive prover, in my opinion.

This assumes you can get the output from debug.

Part of the reason I'm sticking with the `:elab` shell is that, in attempting to write proof scripts outside of it, I can't interpret the error messages.  Small errors produce either tomes of nested data structures or cryptic "nothing to fill in" (separate issue filed).

For example, here's one.

```
When checking right hand side of IntroFail.bid_id_rhs:
Can't run Prelude.Monad.>>= Language.Reflection.Elab.Elab
            Language.Reflection.TTName
            Unit
            {class508}
            (Language.Reflection.Elab.prim__Gensym "b")
            (λ b .
               Prelude.Monad.>>= Language.Reflection.Elab.Elab Unit Unit
                 {class508}
                 (Language.Reflection.Elab.prim__Intro
                    (Prelude.Maybe.Just Language.Reflection.TTName b))
                 (λ {bindx0} .
                    Prelude.Monad.>>= Language.Reflection.Elab.Elab
                      (Prelude.List.List Unit)
                      Unit
                      {class508}
                      (Language.Reflection.Elab.prim__BindElab
                         (Prelude.List.List Language.Reflection.TTName)
                         (Prelude.List.List Unit)
                         (Language.Reflection.Elab.prim__BindElab
                            Language.Reflection.Raw
                            (Prelude.List.List Language.Reflection.TTName)
                            (Language.Reflection.Elab.prim__BindElab
                               (Builtins.Pair Language.Reflection.TTName
                                  Language.Reflection.TT)
                               Language.Reflection.Raw
                               Language.Reflection.Elab.prim__Goal
                               (λ g .
                                  Language.Reflection.Elab.prim__Forget
                                    (Prelude.Basics.snd Language.Reflection.TT
                                       Language.Reflection.TTName
                                       g)))
                            (λ g .
                               Language.Reflection.Elab.prim__BindElab
                                 (Builtins.Pair Language.Reflection.TT
                                    Language.Reflection.TT)
                                 (Prelude.List.List Language.Reflection.TTName)
                                 (Language.Reflection.Elab.prim__Check
                                    (Language.Reflection.Var b))
                                 (λ {bpat0} .
                                    Pruviloj.Induction.case block in induction
                                      (Language.Reflection.Var b)
                                      (constructor of Prelude.Monad.Monad
                                         Language.Reflection.Elab.Elab
                                         (constructor of Prelude.Applicative.Applicative
                                            Language.Reflection.Elab.Elab
                                            (constructor of Prelude.Functor.Functor
                                               Language.Reflection.Elab.Elab
                                               (λ {meth0} .
                                                  λ {meth1} .
                                                    λ {meth2} .
                                                      λ {meth3} .
                                                        Language.Reflection.Elab.prim__BindElab
                                                          {meth0}
                                                          {meth1}
                                                          {meth3}
                                                          (λ x .
                                                             Language.Reflection.Elab.prim__PureElab
                                                               {meth1}
                                                               ({meth2} x))))
                                            (λ {meth0} .
                                               λ {meth1} .
                                                 Language.Reflection.Elab.prim__PureElab
                                                   {meth0}
                                                   {meth1})
                                            (λ {meth4} .
                                               λ {meth5} .
                                                 λ {meth2} .
                                                   λ {meth3} .
                                                     Language.Reflection.Elab.prim__BindElab
                                                       ((__pi_arg3 : {meth4}) →
                                                        {meth5})
                                                       {meth5}
                                                       {meth2}
                                                       (λ g1 .
                                                          Language.Reflection.Elab.prim__BindElab
                                                            {meth4}
                                                            {meth5}
                                                            {meth3}
                                                            (λ y .
                                                               Language.Reflection.Elab.prim__PureElab
                                                                 {meth5}
                                                                 (g1 y)))))
                                         (λ {meth0} .
                                            λ {meth1} .
                                              λ {meth2} .
                                                λ {meth3} .
                                                  Language.Reflection.Elab.prim__BindElab
                                                    {meth0}
                                                    {meth1}
                                                    {meth2}
                                                    {meth3}))
                                      g
                                      (constructor of Prelude.Monad.Monad
                                         Language.Reflection.Elab.Elab
                                         (constructor of Prelude.Applicative.Applicative
                                            Language.Reflection.Elab.Elab
                                            (constructor of Prelude.Functor.Functor
                                               Language.Reflection.Elab.Elab
                                               (λ {meth0} .
                                                  λ {meth1} .
                                                    λ {meth2} .
                                                      λ {meth3} .
                                                        Language.Reflection.Elab.prim__BindElab
                                                          {meth0}
                                                          {meth1}
                                                          {meth3}
                                                          (λ x .
                                                             Language.Reflection.Elab.prim__PureElab
                                                               {meth1}
                                                               ({meth2} x))))
                                            (λ {meth0} .
                                               λ {meth1} .
                                                 Language.Reflection.Elab.prim__PureElab
                                                   {meth0}
                                                   {meth1})
                                            (λ {meth4} .
                                               λ {meth5} .
                                                 λ {meth2} .
                                                   λ {meth3} .
                                                     Language.Reflection.Elab.prim__BindElab
                                                       ((__pi_arg3 : {meth4}) →
                                                        {meth5})
                                                       {meth5}
                                                       {meth2}
                                                       (λ g1 .
                                                          Language.Reflection.Elab.prim__BindElab
                                                            {meth4}
                                                            {meth5}
                                                            {meth3}
                                                            (λ y .
                                                               Language.Reflection.Elab.prim__PureElab
                                                                 {meth5}
                                                                 (g1 y)))))
                                         (λ {meth0} .
                                            λ {meth1} .
                                              λ {meth2} .
                                                λ {meth3} .
                                                  Language.Reflection.Elab.prim__BindElab
                                                    {meth0}
                                                    {meth1}
                                                    {meth2}
                                                    {meth3}))
                                      {bpat0}
                                      {bpat0})))
                         (λ hs .
                            Language.Reflection.Elab.prim__BindElab
                              (Prelude.List.List (Prelude.Maybe.Maybe Unit))
                              (Prelude.List.List Unit)
                              (Prelude.Traversable.Prelude.List instance of Prelude.Traversable.Traversable, method traverse
                                 Language.Reflection.Elab.Elab
                                 Language.Reflection.TTName
                                 (Prelude.Maybe.Maybe Unit)
                                 (constructor of Prelude.Applicative.Applicative
                                    Language.Reflection.Elab.Elab
                                    (constructor of Prelude.Functor.Functor
                                       Language.Reflection.Elab.Elab
                                       (λ {meth0} .
                                          λ {meth1} .
                                            λ {meth2} .
                                              λ {meth3} .
                                                Language.Reflection.Elab.prim__BindElab
                                                  {meth0}
                                                  {meth1}
                                                  {meth3}
                                                  (λ x .
                                                     Language.Reflection.Elab.prim__PureElab
                                                       {meth1}
                                                       ({meth2} x))))
                                    (λ {meth0} .
                                       λ {meth1} .
                                         Language.Reflection.Elab.prim__PureElab
                                           {meth0}
                                           {meth1})
                                    (λ {meth4} .
                                       λ {meth5} .
                                         λ {meth2} .
                                           λ {meth3} .
                                             Language.Reflection.Elab.prim__BindElab
                                               ((__pi_arg3 : {meth4}) → {meth5})
                                               {meth5}
                                               {meth2}
                                               (λ g .
                                                  Language.Reflection.Elab.prim__BindElab
                                                    {meth4}
                                                    {meth5}
                                                    {meth3}
                                                    (λ y .
                                                       Language.Reflection.Elab.prim__PureElab
                                                         {meth5}
                                                         (g y)))))
                                 (Prelude.Basics.flip
                                    (Language.Reflection.Elab.Elab
                                       (Prelude.Maybe.Maybe Unit))
                                    Language.Reflection.TTName
                                    (Language.Reflection.Elab.Elab Unit)
                                    (Pruviloj.Core.inHole Unit)
                                    (Language.Reflection.Elab.prim__BindElab
                                       ((__pi_arg3 : Unit) → Unit)
                                       Unit
                                       (Language.Reflection.Elab.prim__BindElab
                                          Unit
                                          ((__pi_arg6 : Unit) → Unit)
                                          Language.Reflection.Elab.prim__Compute
                                          (λ x .
                                             Language.Reflection.Elab.prim__PureElab
                                               ((__pi_arg6 : Unit) → Unit)
                                               (Prelude.Basics.id Unit)))
                                       (λ g .
                                          Language.Reflection.Elab.prim__BindElab
                                            Unit
                                            Unit
                                            (Language.Reflection.Elab.prim__Try
                                               Unit
                                               (Language.Reflection.Elab.prim__BindElab
                                                  Unit
                                                  Unit
                                                  (Language.Reflection.Elab.prim__Search
                                                     100
                                                     (Prelude.List.Nil
                                                        Language.Reflection.TTName))
                                                  (λ x .
                                                     Language.Reflection.Elab.prim__PureElab
                                                       Unit
                                                       MkUnit))
                                               (Language.Reflection.Elab.prim__PureElab
                                                  Unit
                                                  MkUnit))
                                            (λ y .
                                               Language.Reflection.Elab.prim__PureElab
                                                 Unit
                                                 (g y)))))
                                 hs)
                              (λ x .
                                 Language.Reflection.Elab.prim__PureElab
                                   (Prelude.List.List Unit)
                                   (Prelude.List.catMaybes Unit x))))
                      (λ {bindx2} .
                         Prelude.Monad.>>= Language.Reflection.Elab.Elab Unit
                           Unit
                           {class508}
                           Language.Reflection.Elab.prim__Attack
                           (λ {bindx3} .
                              ? {class566} .
                                Prelude.Monad.>>= Language.Reflection.Elab.Elab
                                  (Language.Reflection.Elab.Elab
                                     Language.Reflection.TTName)
                                  Unit
                                  {class508}
                                  (Prelude.Functor.map
                                     Language.Reflection.Elab.Elab
                                     String
                                     (Language.Reflection.Elab.Elab
                                        Language.Reflection.TTName)
                                     {class566}
                                     Language.Reflection.Elab.Tactics.gensym
                                     (Prelude.List.:: String "x"
                                        (Prelude.List.:: String "ix"
                                           (Prelude.List.:: String "y"
                                              (Prelude.List.:: String "iy"
                                                 (Prelude.List.Nil String))))))
                                  (λ {bpat0} .
                                     ¿ IntroFail.case block in bid_id_rhs .
                                       IntroFail.case block in bid_id_rhs
                                         {class508}
                                         b
                                         {class508}
                                         {bindx0}
                                         {class508}
                                         {bindx2}
                                         {class508}
                                         {bindx3}
                                         {class508}
                                         {class566}
                                         {bpat0}
                                         {bpat0}))))) as an elaborator script.
Is it a stuck term?
```

For the record, that resulted from my attempting to change

```idris
x <- gensym "x"
ix <- gensym "ix"
y <- gensym "y"
iy <- gensym "iy"
```

into

```idris
[x, ix, y, iy] <- traverse gensym ["x","y","ix","iy"]
```

which may very well be invalid, but I can't tell why from that error.

**Comment by cbiffle** [comment]
(And, yes, it still fails if the implicit `case` is made correct by using `Vect`.)

**Comment by david-christiansen** [comment]
This is almost certainly because Idris failed to produce a term for your script - there's likely another error before it which states what the problem is. But I'll modify that error message to not dump the whole script unless asked to - this is definitely intimidating!

I really appreciate your notes as you work through this. Thanks!

**Comment by david-christiansen** [comment]
Ah, this case seems to be a phase restriction issue. If you define the script before you use it, it will not do this.

**Comment by cbiffle** [comment]
Nice catch!  I will add "define scripts at top level and call by name in `%runElab`" to my list of rituals. ;-)  That puts me back firmly in "nothing to fill in" territory, which is more tractable.

**Comment by david-christiansen** [comment]
The phase restriction here is really irritating - I think it's the biggest flaw in the implementation of elaborator reflection, but I think that fixing it properly will basically mean rewriting most of the elaborator. I can probably at least give it a better error message though!

**Comment by cbiffle** [comment]
`rewriteWith` is giving me similar errors to `intro` in certain cases -- should I expect to `attack` / `solve` around `rewriteWith` too?

```
----------              Other goals:              ----------
{hole88},{hole87},{hole86},{BAnd179},{hole0}
----------              Assumptions:              ----------
 b : BExp
 x : BExp
 ix : beval x = beval (bid x)
 y : BExp
 iy : beval y = beval (bid y)
----------                 Goal:                  ----------
{hole89} : beval x && Delay (beval y) =
           beval (bid x) && Delay (beval (bid y))

-IntroFail.bid_id_rhs> rewriteWith (Var `{{iy}})

----------              Other goals:              ----------
{hole88},{hole87},{hole86},{BAnd179},{hole0}
----------              Assumptions:              ----------
 b : BExp
 x : BExp
 ix : beval x = beval (bid x)
 y : BExp
 iy : beval y = beval (bid y)
----------                 Goal:                  ----------
{hole89} : beval x && Delay (beval y) =
           beval (bid x) && Delay (beval y)

-IntroFail.bid_id_rhs> rewriteWith (Var `{{ix}})
INTERNAL ERROR: Can't rewrite here
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
```

(I ask because I'm writing wrappers for these operations that automatically `attack` and `solve`.)

**Comment by david-christiansen** [comment]
Yes, because `rewriteWith` internally produces a `let`-binding of the rewrite rule to be employed.

**Comment by cbiffle** [comment]
This does not seem to be a good universal strategy.

Consider this operation:

```idris
rewriteWith' : Raw -> Elab ()
rewriteWith' r = attack *> rewriteWith r <* solve
```

It doesn't work:

```
----------              Other goals:              ----------
{hole87},{hole86},{hole85},{BAnd178}
----------              Assumptions:              ----------
 b : BExp
 x : BExp
 ix : beval x = beval (bid x)
 y : BExp
 iy : beval y = beval (bid y)
----------                 Goal:                  ----------
{hole88} : beval x && Delay (beval y) =
           beval (bid x) && Delay (beval (bid y))
-IntroFail.bid_id_rhs> rewriteWith' (Var `{{ix}})
Can't infer argument hole to replace
```

Stepping through the equivalent operations manually show that it's `solve` failing.

```
-IntroFail.bid_id_rhs> attack
----------              Other goals:              ----------
{hole88},{hole87},{hole86},{hole85},{BAnd178}
----------              Assumptions:              ----------
 b : BExp
 x : BExp
 ix : beval x = beval (bid x)
 y : BExp
 iy : beval y = beval (bid y)
----------                 Goal:                  ----------
{hole89} : beval x && Delay (beval y) =
           beval (bid x) && Delay (beval (bid y))
-IntroFail.bid_id_rhs> rewriteWith (Var `{{ix}})
----------              Other goals:              ----------
{hole88},{hole87},{hole86},{hole85},{BAnd178}
----------              Assumptions:              ----------
 b : BExp
 x : BExp
 ix : beval x = beval (bid x)
 y : BExp
 iy : beval y = beval (bid y)
----------                 Goal:                  ----------
{hole89} : beval x && Delay (beval y) =
           beval x && Delay (beval (bid y))
-IntroFail.bid_id_rhs> solve
Can't infer argument hole to replace
```

Clearly my attempt to automate the bracketing is too naive; what pattern would you suggest?  Can't very well `try solve` because, if it fails, it leaves the hole pushed by `attack` on the stack (here, `{hole89}`).

**Comment by david-christiansen** [comment]
Right, `solve` needs to be called after the body of the binder is elaborated. If you want to avoid manual `attack` and `solve` operations, you'll probably need to write a DSL that tracks them, and then an interpreter of this DSL into Elab.

Perhaps something like:
```
data BiffleTac : Nat -> Type -> Type where
  ...
  BiffleRewriteWith : Raw -> BiffleTac (S n) -> BiffleTac n
  BiffleIntro : TTName -> BiffleTac (S n) -> BiffleTac n

interp : BiffleTac n a -> Elab a
interp (BiffleRewriteWith tm k) = attack *> rewriteWith tm *> interp k *> solve
...
```
where the `Nat` index ensures that every new hole has a corresponding `solve`.

**Comment by david-christiansen** [comment]
You could also make a version that, after each `>>=`, does something like an `autosolve`:
```
autosolve : Elab ()
autosolve = do (curr, _) <- getGoal; for_ !getHoles (\h => inHole h (try solve)); focus curr
```

**Comment by cbiffle** [comment]
Fair enough.

A DSL may be the right way to go in the long term.  My interest is in applying software engineering to proof construction, i.e. to avoid the Coq mess.  Idris, and your elaborator reflection mechanism, attracted me because it seemed like the most promising place for this to happen.

The current elaborator reflection proofs feel like the assembly language of an abstract machine with lots of implicit state -- somewhat less so than Coq, but still requiring the reader to step through simulations in their head.  (I've been drawing analogies to Forth.)  It might be best for me to treat it that way (as an assembly language) and build a separately structured language atop it.

The current abstractions feel leaky, though this may be due to my own ignorance of the design.  It isn't apparent from the type signature (or docs) of something like `rewriteWith` whether it introduces a let binding under the hood that the programmer will subsequently need to deal with explicitly.  As an API maintainer, my reaction to leaky abstractions is to seal them off behind ones that are harder to misuse, such as combinators to bracket forms with `attack` and `solve` where they are otherwise required by rote.  It's apparent now that the requirement is not *rote* per se, but requires some insight, so I'm not sure I can proceed.  (At least in part because of #2708.)

I look forward to the publication of your dissertation, and congratulations on the impending marriage. :-)

**Comment by david-christiansen** [comment]
#2708 is next on my list of things to investigate!

Really, `Elab` already is the assembly language for a fancy proof construction system - Idris itself! The process of translating Idris to its core language is done using the same operations, though in Haskell rather than in Idris. I'd be really happy to see better proof systems constructed that use `Elab` under the hood as hooks into the complex infrastructure bits, like the type checker and the unifier.

One thing that I'd like to make happen, but that likely won't be there in time for my PhD dissertation, is to implement MTac for Idris with an interpreter that executes in Elab. But what I really envision is having a few different proof DSLs, each specialized to particular kinds of situations. 

In the meantime, I'll get the docs for the tactics updated. And thanks!

**Comment by david-christiansen** [comment]
BTW, for this proof script:
```
||| Proof that the identity transform really is one.
bid_id : (b : BExp) -> beval b = beval (bid b)
bid_id b = %runElab (do [x, ix, y, iy] <- traverse gensym ["x","y","ix","iy"]
                        attack
                        intro x
                        intro ix
                        intro y
                        intro iy)
```
Idris is now returning:
```
- + Errors (1)
 `-- IntroFail.idr line 27 col 7:
     When checking right hand side of bid_id:
     Can't run elaboration script because it contains pattern matching that has not yet been elaborated.
     Try lifting the script to a top-level definition.
     In particular, the problem is caused by: IntroFail.case block in bid_id at IntroFail.idr:27:43
```

where position 27:43 is just to the right of the left arrow in the pattern-matching bind. It should really highlight the pattern, but at least the error is getting you on the right line!

**Comment by ahmadsalim** [comment]
The issue still gives an internal error.
